# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MajorVersion: 0
  MinorVersion: 1 #Decide what would be the versions of build names
  PatchVersion: 0
trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master
    - release/*

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Rev:r)

jobs:
 # Build Development Environment
 - job: Build_Test
   pool:
     vmImage: 'Ubuntu-latest'
   steps:
   # Install prerequisites
   - task: UsePythonVersion@0
     inputs:
       versionSpec: 3.x
       architecture: 'x64'
   - script: |
       python -m pip install --upgrade pip setuptools wheel
       pip install -r requirements.txt
       pip install unittest-xml-reporting
     displayName: 'Install prerequisites'

   # Install terraform & Validating terraform code
   - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
     displayName: 'terraform validate'
     inputs:
       awsCredentials: devsand-vasu
       regionName: 'us-east-1'
       scriptType: inline
       inlineScript: |
         make install_terraform_linux 
         make terraform_validate 
       workingDirectory: '$(System.DefaultWorkingDirectory)/_vasu-ae_test-repo'
    
   # Execute terraform Plan
   - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
     displayName: 'terraform plan'
     inputs:
       awsCredentials: devsand-vasu
       regionName: 'us-east-1'
       scriptType: inline
       inlineScript: |
         make terraform_plan
         make terraform_clean
       workingDirectory: '$(System.DefaultWorkingDirectory)/_vasu-ae_test-repo'

   # Publish Artifact
   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: s3-sync-replication'
     inputs:
       PathtoPublish: '$(Build.SourcesDirectory)'
       ArtifactName: s3-sync-replication
  